apiVersion: v1
kind: ConfigMap
metadata:
  name: vcs-config
  namespace: vcs-system
  labels:
    app.kubernetes.io/name: gamedev-vcs
    app.kubernetes.io/component: config
data:
  # Redis Configuration
  redis.conf: |
    bind 0.0.0.0
    port 6379
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
    databases 16
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data
    maxmemory 1gb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb

  # ClickHouse Configuration  
  clickhouse-config.xml: |
    <?xml version="1.0"?>
    <clickhouse>
        <logger>
            <level>information</level>
            <console>true</console>
        </logger>
        
        <http_port>8123</http_port>
        <tcp_port>9000</tcp_port>
        
        <listen_host>0.0.0.0</listen_host>
        
        <max_connections>4096</max_connections>
        <keep_alive_timeout>3</keep_alive_timeout>
        <max_concurrent_queries>100</max_concurrent_queries>
        <uncompressed_cache_size>8589934592</uncompressed_cache_size>
        <mark_cache_size>5368709120</mark_cache_size>
        
        <path>/var/lib/clickhouse/</path>
        <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
        <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
        
        <users>
            <default>
                <password></password>
                <networks incl="networks" replace="replace">
                    <ip>::/0</ip>
                </networks>
                <profile>default</profile>
                <quota>default</quota>
            </default>
        </users>
        
        <profiles>
            <default>
                <max_memory_usage>10000000000</max_memory_usage>
                <use_uncompressed_cache>0</use_uncompressed_cache>
                <load_balancing>random</load_balancing>
            </default>
        </profiles>
        
        <quotas>
            <default>
                <interval>
                    <duration>3600</duration>
                    <queries>0</queries>
                    <errors>0</errors>
                    <result_rows>0</result_rows>
                    <read_rows>0</read_rows>
                    <execution_time>0</execution_time>
                </interval>
            </default>
        </quotas>
    </clickhouse>

  # VCS API Configuration
  vcs-config.env: |
    ENVIRONMENT=production
    PORT=8080
    STORAGE_PATH=/app/storage
    GIN_MODE=release
    
---
apiVersion: v1
kind: Secret
metadata:
  name: vcs-secrets
  namespace: vcs-system
  labels:
    app.kubernetes.io/name: gamedev-vcs
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded secrets - replace these with actual values
  jwt-secret: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=  # "change-me-in-production"
  clickhouse-password: ZGV2X3Bhc3N3b3Jk  # "dev_password"
  redis-password: ""  # Empty for no auth in development
  
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: vcs-system
  labels:
    app.kubernetes.io/name: gamedev-vcs
    app.kubernetes.io/component: backup
type: Opaque
data:
  # AWS credentials for S3 backup (base64 encoded)
  aws-access-key-id: ""
  aws-secret-access-key: ""
  aws-region: dXMtZWFzdC0x  # "us-east-1"